---

language: node_js

node_js:
  - lts/*
  - 10
  - 8

git:
  depth: 1

before_script:
  - cp ./test/fixtures/config.js ./config.js

script:
  - npm run build
  - npm run lint
  - npm run test

services:
  - mongodb

addons:
  apt:
    sources:
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
