---

language: node_js

sudo: required

services:
  - docker

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev

node_js:
  - node
  - lts/*

cache:
  directories:
    - /tmp/liftoff

before_install:
  - docker pull ubuntu:16.04

script:
  - npm run build
  - npm run lint
  - npm run ci
