language: node_js

git:
  depth: 1

script:
  - npm run build
  - npm run lint
  - npm run test

# When we work with database tests, this is the travis config we will need
# services:
#   - mongodb
#
# addons:
#   apt:
#     sources:
#       - mongodb-3.0-precise
#     packages:
#       - mongodb-org-server
