---

language: node_js

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev

node_js:
  - 6
  - 7

script:
  - yarn build
  - yarn lint
  - yarn coverage
