---

language: node_js

sudo: required

services:
  - docker

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev

node_js: lts/*

cache:
  directories:
    - /tmp/liftoff

script:
  - npm run build
  - npm run lint
  - npm run ci

jobs:
  include:
    - stage: Setup
      script: docker pull ubuntu:16.04
      # TODO: Pull testing docker images
      # TODO: Warm up liftoff cache

    - stage: Test
      node_js: lts/*
    - node_js: 9
    - node_js: 8
    - node_js: 6

    - stage: Release
